#!/usr/bin/env bash
# Regenerate docs/reference/subsystem-map.md — the bottom-up navigation index — from the
# installed extensions' catalog + COMMENT ON subsystem markers. Pinned to one PostgreSQL
# version so output is stable; the CI "Subsystem map up to date" gate runs this and fails
# if the committed file differs. Sibling of scripts/gen-reference.sh.
#
#   scripts/gen-subsystem-map.sh
set -euo pipefail
cd "$(dirname "$0")/.."

export PG_VERSION="${PG_REF_VERSION:-17}"
COMPOSE=(docker compose
         -f docker-compose.yml
         -f pgfc_observe/docker-compose.yml
         -f pgfc_govern/docker-compose.yml)

cleanup() { "${COMPOSE[@]}" down -v --remove-orphans >/dev/null 2>&1 || true; }
trap cleanup EXIT
cleanup
"${COMPOSE[@]}" up -d --build >/dev/null

echo "Waiting for database to become healthy..." >&2
status=""
for _ in $(seq 1 60); do
  cid=$("${COMPOSE[@]}" ps -q db)
  status=$(docker inspect -f '{{.State.Health.Status}}' "$cid" 2>/dev/null || echo "starting")
  [ "$status" = "healthy" ] && break
  sleep 2
done
[ "$status" = "healthy" ] || { echo "database never became healthy" >&2; exit 1; }

PSQL=(psql -U postgres -d pgfc_test -v ON_ERROR_STOP=1 -X -q)
"${COMPOSE[@]}" exec -T db "${PSQL[@]}" -f /sql/pgfc_observe/install.sql >/dev/null
"${COMPOSE[@]}" exec -T db "${PSQL[@]}" -f /sql/pgfc_govern/install.sql  >/dev/null

mkdir -p docs/reference
# Command substitution strips trailing newlines; printf re-adds exactly one, so the file
# ends with a single newline and no trailing blank lines (markdownlint MD012).
content=$("${COMPOSE[@]}" exec -T db \
    psql -U postgres -d pgfc_test -X -q -t -A -P footer=off \
    < scripts/gen_subsystem_map.sql)
{
  echo "<!-- GENERATED by scripts/gen-subsystem-map.sh — do not edit. -->"
  echo
  printf '%s\n' "$content"
} > docs/reference/subsystem-map.md
echo "wrote docs/reference/subsystem-map.md" >&2
